BE/Level_4/learning_templates/basic_app/urls.py
from django.urls import path
from django.urls.resolvers import URLPattern
from . import views

#TEMPLATE TAGGING
app_name = 'basic_app'
urlpatterns = [
    path('relative/', views.relative, name='relative'),
    path('other/', views.other, name='other')
]

BE/Level_4/learning_templates/learning_templates/urls.py
from django.urls.conf import include
from django.contrib import admin
from django.urls import path
from basic_app import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index, name='index'),
    path('basic_app/', include('basic_app.urls'))
]

BE/Level_4/learning_templates/basic_app/models.py
from django.db import models

# Create your models here.

BE/Level_4/learning_templates/basic_app/views.py
from django.shortcuts import render

# Create your views here.
def index(request):
    context_dict = {'text':'hello world!', 'number':100}
    return render(request,'basic_app/index.html', context_dict)

def other(request):
    return render(request,'basic_app/other.html')

def relative(request):
    return render(request,'basic_app/relative_url_templates.html')

BE/Level_4/learning_templates/templates/basic_app/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css"
    integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

</head>
<body>
    <nav class="navbar navbar-default navbar-static-top">
        <div class="container">
            <ul class="nav navbar-nav">
                <li><a class="navbar-brand" href="{% url 'index' %}">HOME</a></li>
                <li><a class="navbar-link" href="{% url 'admin:index' %}">Admin</a></li>
                <li><a class="navbar-link" href="{% url 'basic_app:other' %}">Other</a></li>
            </ul>
        </div>
    </nav>
    <div class="container">
        {% block body_block %}
        <!-- Anything outside of this will be inherited if you extend -->
        {% endblock %}
    </div>
</body>
</html>

BE/Level_4/learning_templates/templates/basic_app/index.html
<!DOCTYPE html>
{% load my_templates %}
{% extends "basic_app/base.html" %}
    {% block body_block %}
        <h1>Welcome to Index!</h1>
        <h2>This is index.html page showing!</h2>
        <!-- <h1>{{ text|upper}}</h1> -->
        <h1>{{ text|cut:'world'}}</h1>
        <h1>{{ number|add:'99' }}</h1>
        {% endblock %}

BE/Level_4/learning_templates/templates/basic_app/index_old.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Index</title>
</head>
<body>
    <h1>Welcome to Index!</h1>
    
</body>
</html>

BE/Level_4/learning_templates/templates/basic_app/other.html
<!DOCTYPE html>
{% extends "basic_app/base.html" %}
    {% block body_block %}
        <h1>Welcome to Other!</h1>
        <h2>This is an example of template inheritance!</h2>
        {% endblock %}

BE/Level_4/learning_templates/templates/basic_app/other_old.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Other</title>
</head>
<body>
    <h1>Welcome to Other!</h1>
    <a href="{% url 'basic_app:relative' %}">THE RELATIVE PAGE</a>
    
</body>
</html>

BE/Level_4/learning_templates/templates/basic_app/relative_url_templates.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>URL Templates</title>
</head>
<body>
    <h1>Welcome to Relative URL Templates!</h1>
    <a href="{% url 'basic_app:other' %}">THE OTHER PAGE</a>
    <a href="{% url 'admin:index' %}">LINK TO ADMIN</a>
    <a href="{% url 'index' %}">LINK TO INDEX</a>

</body>
</html>